# Õpihuumor

## Tantsimine aluspesuväel

Et paarissessioon on liiga pikk, otsustasime selle keskele tekitada vahepala, milleks ma pakkusin välja, et tantsime. Iga kord pidi keegi meist koreograafika ette valmistama ja siis me kõik pidime selle läbi tantsima. Tavaliselt olime tantsijateks mina ja kaks ukraina poissi. Oli külm talv ja ühel poistest hakkas palav ning ta küsis mult, kas võib pealmised püksid ära võtta. Lubasin. Kui siis olime parasjagu tantsuhoos, tema pikkade aluspükste väel, sisenes ruumi hoopis teises asjas naissoost koordinaator.

## Arusaamatu lause

Õpilane kirjutas oma protokolli:

> Elektrostaatikat saime pulga sisse seda hõõrudes elektrostaatikat võimelise ülekandega riiet

`r librarian::shelf(c("tufte"));  tufte::quote_footer('--- Sten-Erik Mihkelson')`

> Staatika on tasakaal. Pakun, et tasakaal oli ka enne hõõrumist, sest tasakaal on süsteemis alati. Pigem, kui vaadelda ainult pulka, siis hõõrudes läheb pulga laeng just tasakaalust ehk nullväärtusest välja. Ehk mõtlesid hoopis nullist erineva laengu kujundamist? Ühtlasi on see lauseosa katki. Igatahes on see lause esimene tõeline mittekatsutav füüsikapärl ja keegi võib saada selle lause osade lahtiseletamise reedeses testis ülesandeks.

`r librarian::shelf(c("tufte"));  tufte::quote_footer('--- Kalmer Piiskop • 19:18, 3. okt (EEST)')`

## Sõrmega masturbeerimine

Üks naisõpilane asus alati, kui oli minu antud ülesanded lahendanud, tahvelarvutiga sõrmedega alade tabamise mängu mängima. Ükskord pausi kestel, kui ta taas seda tegi, kommenteerisin: "So you are practicing your fingering skills," mõeldes sõrmede motoorika harjutamist. Neiu vaatas mulle tõsise näoga otsa: "Don't use that word!" Mul kulus veidi aega, et aru saada, kuidas tema minu ütlust mõistis.

## Naiselikud meesõpilased

Selgitasin vene õpilastele hulki näite varal, milles ühes hulgas on meesõpilased ja teises hulgas naisõpilased. Ütlesin "мужские ученики" ja "женские ученики". Publiku seast kostis itsitamist ja üks neiu ütles, nii ei olevat ilus öelda. Olin unustanud, et vene keeles on sood ja naisõpilased on lihtsalt "ученицы".

## Muide

Olin tükk aega vene õpilastele enda arvates väga lihtsalt selgitanud, kuidas panna midagi millegi asemele, aga nad ei saanud hästi aru, kuni ma ühelt õpilaselt küsisin, kas ma üldse õiget sõna kasutan. Ma olin öelnud umbes nagu: "Постави 2 кстате *x*." Tahtsin öelda, et ta paneks kahe *x*-i asemele, aga olin alati öelnud hoopis nagu: "Pane 2 muide *x*."

## Kivi

Tegime õpilastega juturingi, et nende kaebusi minu suhtes arutada. Reegel oli, et räägib, kelle käes on kivi, ja teised kuulavad. Üks õpilane asus ilma kivita mind negatiivselt kritiseerima ja kui ta oli mõne lause öelnud, küsisin: "Doris, kas sa tahad kivi saada?"
