# Kiidud

## Mis?

Sinimäe Põhikooli õpetajate toas on silt:

> Mille eest sa täna end kiidaksid?

Jäin ükskord mõtlema sellele ega suutnud leida vastust. Ühes päevas tundsin, et sedapuhku tean vastust ja otsustasin oma vastused siia üles kirjutada.

## 2025-10-2

Kiidan end, et suutsin oma plaanitud meisterdamistegevusega aktiveerida kõik kohalolnud kaheksanda taseme õpilased. Ilmselt neile, kes muidu ei viitsi kaasa teha, on käeline töö meelepärane. Paistab, mis saab, kui nad selle käelise töö tulemusega hakkavad andmeanalüüsi teostama.

## 2025-10-3

Kiidan end, et pesin seebiga jalad üsna vahetult enne tudengite kohtumist ja kandsin edaspidi susse, sest Baabuki tennised ei paista olevat mõeldud tundidekaupa sokkideta kandmiseks. Hais oli jube. Lisaks oli kulunud naha pealiskiht nii keskmise parema varba all kui parema jalatalla keskel muutes kõndimise valuliseks.

## 2025-10-4

Kiidan end, et pärast magamaminekut kesköö paiku vms ei tõusnud ma voodilt enne kella 16, sest soovisin võimalikult välja puhata möödunud pingutustest ja olla valmis järgmisteks pingutusteks. Arvan, et magamise kestus rohkete pauside ja unenägudega oli \\qty{16}{\\hour}.

## 2025-10-5

Kiidan end, et suutsin aidata õpilasel Päikesesüsteemi planeedid teada saada.

## 2025-10-6

Kiidan end, et Linnaorienteerumises ikka punkti *32* üles otsisin, kuigi selleks kulus üles poole tunni.

## 2025-10-7

Kiidan end, et analüüsisin üheksanda taseme lähtetesti sooritused lõpuni. Kui matemaatikas kaks kolmandikku õpilasi ei mäletanud või olnud õppinud piisavalt, siis keemias ainult viis õpilast 16'st. Kas see näitab, et matemaatika oli liiga vähe lõimitud praktikaga?

## 2025-10-8

Kiidan end, et otsustasin enne magada ja pärast ette valmistada. Tõusin kella viie paiku ja olin ergas. Koolipäev oli siiski stressirikas: oli vaja tegeleda paljude õpilaste käitumisprobleemidega ja pärast põhikoolis õpetamist tundsin end uimasena ja maailm nagu veidi kõikus-keerles. Siis tuli ka veidi uni peale, aga muidu pidasin lõpuni vastu.

## 2025-10-9

Kiidan end, et asusin kolleegiumis otsima lahendust üheksanda aasta õpilaste käitumishäiretele. Olukord läks nii hulluks, et enamus õpilasi keeldus õppimast, nõuti eelmist õpetajat, kooli poolt antud õpiku ja töövihiku kasutamist, mind mõnitati, osatati, grupiviisiliselt hoiti nutitelefone püsti enda ees, justkui jäädvustataks mind. Üks õpilane siiski jätkas õppimist laskmata end segada ümbritsevast möllust. Rääkisin siis rühmajuhiga, kes väitis, et ka temal on sarnaseid probleeme nendega. Seejärel rääkisin õppejuhiga, kes pakkus välja, et proovime siis õpiku ja töövihiku kasutamist. Ka haridusvolinikuga rääkisin, kes soovitas mentorit õppesessioonidesse. Ühiskonnaõpetaja väitis, et neid õpilasi suudaks paika panna ainult vene õpetaja sõimates neid õige tonaalsusega vene sõimusõnadega.

## 2025-10-11

Kiidan end, et suutsin ülemineku õpiku ja töövihiku kasutamisele kiiresti korraldada.

## 2025-10-12

Kiidan end, et loobusin edasisest glögidžinni joomisest, kuna sain migreenihoo üle poole aasta mainitud stressi ja magamatuse tõttu.

## 2025-10-13

Kiidan end, et nautisin tennist ja oma esimesele naispartnerile ei öelnud negatiivset kriitikat, mille eest ta mind tänas.

## 2025-10-14

Kiidan end, et sain matemaatika õpiväljundite skeemi tehtud ja seinale.

## 2025-10-15

Kiidan end, et jõudsin ülikooli jaoks teha piisavalt slaide, et aega kohapeal üle ei jääks.

## 2025-10-16

Kiidan end, et läksin ööbimiskohta jõudnuna kohe magama, kuigi und jagus ainult paariks tunniks.

## 2025-10-17

Kiidan end, et valisin hilisema rongi, sest nii sain nautida koolituse kõige lõbusamat osa.

## 2025-10-18

Kiidan end, et pärast \qty{12}{\kilo\m} jooksmist käisin Tibula supluskohas frigidaariumit kogemas, misjärel oli munand nagu lapsel ja pissimine valulik.

## 2025-10-19

Kiidan end, et võtsin ette *Ubuntu* uuendamise oma arvutis, sest muidu ma poleks selleni jõudnud, et ilma pika toeta versiooni ei tasu panna põhiarvutisse.

## 2025-10-20

Kiidan end, et panin astrofüüsika koolituse jäädvustama ja magasin sel ajal, kuna olin ropult väsinud pärast hommikuni operatsioonisüsteemiga jändamist ja hommikust autohooldust.

## 2025-10-21

Kiidan end, et panin ka teise astrofüüsika koolituspäeva jäädvustama ja magasin sel ajal, sest uni on tähtsam. Vaatan puhanuna.

## 2025-10-22

Kiidan end, et Narva "Maksimarket"-s ootasin ära, kuni üks mees sooja söögi letist midagi ostis, et näha, et talle pandi kollane kleeps. Muidu seal olid kõik ilma kaaneta. Kui keegi ostis, saigi \qty{30}{\percent} alla.

## 2025-10-23

Kiidan end, et tõusin juba kell 9, olles väsinud, aga siiski maganud oma kümme tundi, ja asusin ümber korraldama nõudmiste analüüsi novembri praktikumi, sest olin unustanud kontrollida, kas Füüsikaõpetajate sügisseminar on samaaegselt. Protsess oli konarlik. Pidin saama tudengitelt nõusoleku ja pärast sain veel sugeda, et kuna meil on leping, siis ma ei tohtivat mingeid muudatusi soovida.

## 2025-10-24

Kiidan end, et märkisin õpilastele, kes iseseisva õppe päeva ülesandeid ei lahendanud, Stuudiumi "tegemata", mitte "1", sest muidu jääks see samm tegemata. Ainult üks õpilane jäi selle märketa ja too polnud üldse mitte too õpilane, kelle ma arvasin, et on.

## 2025-10-25

Kiidan end, et vahetasin voodipesu. Viimati vahetasin suves.

## 2025-10-26

Kiidan end, et läksin Pühalisse orienteeruma, sest see on väga ilus koht, kus teha jõuluorienteerumist, ja seal sai ka ilusas puhtas kohas supelda.

## 2025-10-27

Kiidan end, et valmistasin põhjalikult keemia õpetamise alusteemat ette.

## 2025-10-28

Kiidan end, et sain hästi hakkama lapsevanemate koosolekus, sest ka direktori kohusetäitja ütles, et hästi esinesin.

## 2025-10-29

Kiidan end, et pakkusin tudengitele välja lisakohtumiste võimalused, mida üks tudeng ka soovis kasutada.

## 2025-10-30

Kiidan end, et märkisin õpilasele Stuudiumi kiituse, sest pseudojuhuslikkuse alusel lasin eelnevalt arvutil välja valida õpilase, küsisin tollelt õpilaselt, mille eest tema end kiidaks täna ning ta vastas, et ta tegi ja mõtles kaasa ning tõepoolest, kogesin, et ta seeläbi omandas ka uut teadmist seoses harmoonikutega. Järgmises päevas üks õpilane väitis, et ma kunagi ei märkivat kiitusi Stuudiumi. Küsisin õpilaselt, kellele ma olin märkinud, kas ma märkisin, ja ta kinnitas teisele õpilasele, et sai kiituse Stuudiumi.

## 2025-10-31

Kiidan end, et kolisin oma reserveeritud kohalt rongis neljasesse laudkonda, mis oli vabastatud, kuna seal oli mul palju rohkem ruumi asjatada. Kiviõlist tulid küll vene kaunitarid mulle vastu, kellest vanem mind kogemata jalaga togis, mis oli põhjuseks vastastikuseks naeratamiseks.

## 2025-11-1

Kiidan end, et kosmosekoolitust söömise kõrvale vaadates slaidilt vesinikust heeliumi valmistamise kohta lugedes tekkis idee selle põhjal tuumasünteesi kirjeldada õpilastele aatomi ehituse teemas ning siis selle kohta ka uurisin.

## 2025-11-2

Kiidan end, et käisin nii orienteerumas kui tennist mängimas ning tegin seda kõike üle keskmise hästi, mis sellest, et üks kontrollpunkt jäi läbimata ja üks tennisemäng sai ühe geimiga kaotatud.

## 2025-11-3

Kiidan end, et suutsin oma orienteerumispükste pesus sisseimetud nööri otsa siiski kätte saada. Aega kulus selleks vist üle poole tunni. Lõpuks aitas see, et tegin kirjaklambrist konksu, lükkasin selle auku, kust pidanuks nöör välja tulema, tõmbasin konksuga nii kaua, kuni sain otsa kätte. Tegin kaks sõlme peale ja edaspidi tuleb pesuks otsad kokku sõlmida.

## 2025-11-4

Kiidan end, et kolisin rongis laudkonda, kus küll keegi diagonaalis vastas istus, ent kaks vaba istet kõrvuti oli, sest keegi oli minu vabasse neljasesse laudkonda otse minu kõrvale broneerinud koha ja laiutas alul minugi kohal.

## 2025-11-5

Kiidan end, et panin märkuse kõigile minu vara ründamises kahtlustatavatele õpilastele, sest tasapisi hakkas laekuma infot, kes mida tegi.

## 2025-11-6

Kiidan end, et sain õpilaselt, keda kahtlustatakse seebi valamises minu säärikusse, ütluse.

## 2025-11-7

Kiidan end, et taas vahetasin oma istekoha sinna, kus on rohkem ruumi.

## 2025-11-8

Kiidan end, et ühe muu füüsikaõpetaja kirjale vastasin, sest ma ei oska end millegi muu eest selles päevas kiita, kui välja arvatud see, et magasin piisavalt.

## 2025-11-9

Kiidan end, et Saku jões ära käisin.

## 2025-11-10

Kiidan end, et üheksanda aasta õpilaste füüsika lähtetesti sooritused kõik lõpuni analüüsida jõudsin.

## 2025-11-11

Kiidan end, et sõidus Ida-Virru tegin peatuse õigeaegselt suvalises kohas, mis osutus ilusaks.

## 2025-11-12

Kiidan end, et suutsin vaatamata süvaettevalmistuse puudumisele tudengitele piirväärtust ja pidevust tutvustada.

## 2025-11-13

Kiidan end, et pakkusin "Kolleegile külla" raames kolleegile täiendust.

## 2025-11-14

Kiidan end, et valisin esimeseks töötoaks füüsikaõpetajate sügisseminaris Kuu pöörlemisperioodi arvutamise piltide põhjal arvutatud koordinaatide alusel, sest see oli põhjalik konkreetne protsess.

## 2025-11-15

Kiidan end, et sõitsin vastavalt teeoludele harjumatult väikese kiirusega, sest tee oli hooldamata.

## 2025-11-16

Kiidan end, et otsustasin tennisemängus "kohal olla", sest tundus, et ma olen mõtetes võimalikus tulevikus.

## 2025-11-17

Kiidan end, et suutsin oma lauaarvutist automaatse kerimise eemaldada. Kulus küll mitu tundi ja eri tarkvaraliste muudatuste katsetamist, kuni taipasin hiire Bluetoothi jubina eemaldada.
