# Kohustuslikud kompetentsid[@a2024_kutsestandardid]

## Õppija toetamine

### Teadlikkus õppija arengust ja õppimisest

Tegevusnäitaja:

> on teadlik õppija füüsilise, kognitiivse, emotsionaalse ja sotsiaalse arengu alustest ning kultuurilistest eripäradest.

Õpetajana mõistan, et õppija arengu toetamine on terviklik protsess, mis hõlmab füüsilisi, kognitiivseid, emotsionaalseid ja sotsiaalseid aspekte. Minu igapäevane töö põhineb teadmistel arengu erinevatest etappidest ning õppijate individuaalsetest ja kultuurilistest eripäradest, mis mõjutavad nende õpiprotsessi ja heaolu.

Füüsilise arengu toetamisel arvestan, et õppijad vajavad liikumist ja paindlikkust õppekorralduses. Kuna liikumine soodustab keskendumist ja üldist heaolu, olen aegajalt korraldanud mittekehalise teema õpet liikumise kaudu. Tennisetreenerina oli liikumine kaasatud õppeprotsessi loomuliku osana. Füüsikaõpetajana viisin Kohila Gümnaasiumis (KG) õpilaste testimist läbi MathCityMapiga, mis võimaldas õpilastel vaheldada vaimset ja füüsilist tegevust. Arvutiteaduse klubis korraldasin orienteerumismänge, milles tuli lahendada arvutiteadusega seotud ülesandeid kasutades orienteerumiskaarti. Matemaatikaõppesse olen kaasanud käelist tegevust, muuseas paberlennukite lennutamist ja nihke mõõtmist üksliikmete teema praktilise ülesandena.

Kognitiivse arengu toetamiseks kasutan diferentseeritud õpet, lähtudes õpilaste arengutasemest ja individuaalsetest vajadustest. Olen teadlik, kuidas arenevad õppija mõtlemis- ja probleemilahendusoskused, ning kujundan õppetegevusi, mis toetavad nii lihtsamate teadmiste omandamist kui ka keerukamate probleemide lahendamist. Narva Täiskasvanute Koolis (NTK) olen matemaatikaõpetajana koostanud igale õpilasele individuaalse õppejärje, et võimaldada oma varasemate lünkade teadmistes ja oskustes täitmist ning ajakohase õppekava järgsete teemade õppimist õpilase omas tempos. Arvutiteaduse õppes lasen õpilastel tegutseda individuaalseid ülesandeid täites omas tempos. Tallinna Vabas Waldorfkoolis (TVW) on minu juhendada põhirühmaga tempost väiksema tempoga õpilased, kelle jaoks katsetan erinevaid meetodeid, et õpilastes tekiksid vajalik arusaam ja oskus õpitud teadmisi kasutada.

Emotsionaalse arengu puhul pööran tähelepanu õppijate heaolu ja motivatsiooni toetamisele. Püüan klassiruumi tuua empaatilise ja avatud õhkkonna, kus õppijad tunnevad end väärtustatuna ja turvaliselt. Olen valmis märkama emotsionaalseid raskusi ning vajadusel suunama õpilasi sobivatele tugiteenustele. Julgustan õpilasi rääkima oma muredest, et parema mõistmise puhul osata aidata õppida. TVW's täheldasin, et üks õpilane kippus spikerdama. Selgitasin kui oluline on testida tema hetke teadmisi-oskusi ja et spikerdamine selle testi rikuks. Ütlesin, et kui ta ausalt välja näitab, mida ta oskab ja teab, isegi kui need teadmised-oskused on olematud, siis saan teda oluliselt täpsemalt juhendada. Tema mõistis ja on edaspidi spikerdamist vältinud. Sama õpilase kätel märkasin hiljem lõikearme. Ta selgitas, et ta kunagi tegi neid ärevusest sunnitud esinemise ees. Kui õpilane tunneb, et saab oma muredest õpetajaga rääkida, on temas vähem ärevust ja tal on turvalisem õppekeskkond. Kuigi tutvustan iga kursuse või õppeaasta alguses enda reegleid, jätan õpilastele ruumi ettepanekute tegemiseks ja läbirääkimiseks. Kui õpilane on avaldanud soovi mingi muu kui selle õppeteemaga tegeleda, mis on minu poolt plaanitud, kuid on siiski õpitava temaatikaga seotud ja ta tunneb, et talle on seda rohkem vaja või see teda eriliselt huvitab, siis võimalusel olen talle seda võimaldanud, et hoida tema sisemist õpimotivatsiooni. Mulle on öeldud õpilaste poolt, et olen tasakaalukas ja rahulik ning selgitan. Sain selleks olulise motivatsiooni oma kunagiselt kolleegilt Postimees Online's lauri tiituselt, kes juba minu eeltestimises rahulikult ja empaatiliselt mind juhendas.

Sotsiaalset arengut edendan, pakkudes õppijatele võimalusi teha koostööd ja osaleda grupitöös, kus nad õpivad suhtlema, teisi kuulama ja vastastikku arvestama. Püüan luua klassis sõbraliku ja toetava õhkkonna, kus väärtustatakse mitmekesisust ja austatakse erinevaid vaatenurki. (siia ühisarutelude pilte) Audenteses International Baccalaureate'i Diploma Programme's arvutiteaduse õpetajana käsitlesime kord moraali ja eetika temaatikat ning saime tunda eri õpilaste erinevat moraali (trammi ülesanne).

Arvestades kultuurilisi eripärasid, toon õppetöösse erinevaid perspektiive, mis võimaldavad õpilastel mõista ja väärtustada mitmekesisust. Samuti püüan luua individuaalset lähenemist, mis arvestab õpilaste kultuurilist tausta, keelelist mitmekesisust ja maailmapilti. Olen õpetanud kahes koolis, milles enamus minu õpilasi eesti keelt selles õppimiseks piisavalt ei osanud. Narva Täiskasvanute Kooli võtsin kaasa Edu Valemis õpitu, et eesti keelt peale suruda ei tohi, vaid õppetegevus sujub oluliselt paremini, kui on võimalik suhelda õpilasega tema emakeeles. Kohila Gümnaasiumis oli mul vahetusõpilane Saksamaast ning temaga eraldi suheldes kasutasin saksa keelt, ühisaruteludes inglise keelt, et ka eesti õpilased mõistaksid.

Oma tegevustes rakendan kaasaegseid teaduslikke teadmisi laste ja noorte arengu kohta ning hoian end pidevalt kursis uute uurimuste ja parimate praktikatega. Selline teadlikkus aitab mul kujuneda empaatilisemaks ja tõhusamaks õpetajaks toetamaks igakülgselt õppijate arengut. Lisaks teadusartiklitele loen ja kuulan huviga arutelusid pedagoogikast. Nii mängis mul kunagi taustaks Roosa Raadio[@roosa]. Huviga jälgisin sarja *Maailma kõige targem rahvas*[@err_2025].

Tegevusnäitaja:

> on teadlik õppimist mõjutavatest teguritest ja seaduspärasustest, üldpädevustest, grupiprotsessidest ja õppija toetamise tõenduspõhistest võimalustest, sh refleksioonimudelite kasutamise vajalikkusest.

Õpetajana mõistan, et õppimise protsessi mõjutavad nii individuaalsed kui ka grupiga seotud tegurid, mille teadvustamine ja arvestamine on õppijate toetamisel ja nende potentsiaali arendamisel määrava tähtsusega. Pean tähtsaks tunda õppimise seaduspärasusi, üldpädevuste arendamist, grupiprotsesside juhtimist ning refleksiooni.

Olen teadlik, et õppimisele avaldavad mõju mitmed individuaalsed ja välised tegurid, nagu õppija kognitiivsed võimed, motivatsioon, eelnev kogemus, emotsionaalne heaolu, füüsiline keskkond ning sotsiaalsed suhted:  
- **Kognitiivsed tegurid**: Kohandan õppeülesandeid vastavalt õppijate võimetele ja eelteadmistele, et tagada õppimise optimaalne raskusaste. Kasutan diferentseeritud õpet, et toetada nii kiiremaid kui ka rohkem tuge vajavaid õppijaid.  
- **Motivatsioon ja emotsioonid**: Kasutan tunnis meetodeid, mis aitavad suurendada sisemist motivatsiooni, pakkudes ülesandeid, mis on õpilaste jaoks tähenduslikud ja seotud päriseluga. Asusin 2021 süvaõppima integreeritud loodusteadusi Tallinna Ülikooli, et osata seostada õpetatavaid teemasid fundamentaalsete loodusteadustega. Samuti pööran tähelepanu positiivse emotsionaalse keskkonna loomisele, mis toetab enesekindlust ja õppimisjulgust.  
- **Keskkond ja sotsiaalne dünaamika**: Loome klassiga ühiselt reegleid ja ootusi, et tagada toetav ja koostööpõhine keskkond. Füüsilist keskkonda korraldan nii, et see soodustaks keskendumist ja mugavust.

Üldpädevused, nagu enesemääratluspädevus, suhtlusoskus, sotsiaalne kaasatus ja digitaalne kirjaoskus, on igapäevase õppetöö loomulik osa. Kujundan õppetööd nii, et:
- õpilased saaksid arendada **kriitilist mõtlemist** ja probleemilahendust, nt kaasates arutelusid ja avatud ülesandeid,
- edendatakse **koostööoskusi**, pakkudes grupitöid ja projektipõhiseid ülesandeid,
- õpilased omandavad **iseseisva õppimise oskused**, toetades neid eesmärkide seadmises ja oma töö reflekteerimises.

Grupiprotsesside teadlik juhtimine aitab kaasa klassi positiivse ja tulemusliku õhkkonna loomisele: 
- **Koostöö ja ühtsuse soodustamine**: Algatan tegevusi, mis aitavad õppijatel luua omavahel tugevaid suhteid ja väärtustada üksteise panust. Näiteks olen läbi viinud teadmiste-oskuste testimist rühmaviisiliselt, mis võimaldab õpilastel üksteise lünki teadmistes-oskustes täita[@a2025_mathtrailpindpinevuspdf; @a2025_mathtrailkeemiaalusedpdf; @a2025_mathtrailvalemikinemaatikapdf; @a2025_mathtrailvoolutugevusetestpdf; @a2025_school; @a2025_mathtrail4tubapdf]. Tallinna Ülikoolis juhtisin Erialasid Lõimiva Uuenduse (ELU) projekti orJenteerumismäng[@a2022_orjenteerumismng], mille kestel lõid tudengid rühmiti MathCityMapi teaduslike faktidega, kestliku arengu eesmärkidega, oma valdkonnaga ja matemaatikaga seotud õpperadu[@a2025_mathtrailtraffictrailpdf; @a2025_mathtrailtrailfromvladpdf]. TVW's lasin ChatGPT'l[@openai_2025_chatgpt] vastavalt õpiväljundile ja Bloomi 2001. a taksonoomia[@quevillon_2018_blooms] tasemetele õpilastega vesteldes nende teadmisi-oskusi testida, nii et õpilased tohtisid omavahel arutada ja ühiselt otsustada, mida vastata. Matemaatikaõppes olen lasknud õpilastel praktilisi ülesandeid lahendada rühmiti.  
- **Konfliktide lahendamine**: Olen valmis märkama ja lahendama klassis tekkivaid pingeid ning õpetama õpilastele konfliktide ennetamise ja lahendamise oskusi. Toetan õpilasi dialoogis, kus austatakse teineteise seisukohti. Julgustan õpilasi kohe küsima, kui miski on arusaamatu või õpilase arvates valesti tehtud.

Õppija toetamiseks rakendan tõhusaid praktikaid:
- Kasutan **formatiivset hindamist**, mis annab õpilastele regulaarset tagasisidet nende edusammude kohta ja võimaldab parandada õppeprotsessi.
- Kombineerin **aktiivõppe meetodeid**, näiteks probleemõpet ja projektipõhist õpet, mis arendavad õpilaste analüüsivõimet ja meeskonnatööoskusi. Lisaks ELU-projektile viisin Tallinna Kunstigümnaasiumi projektipäevade raames läbi praktilisi projekte[@a2025_staatilise; @a2025_staatilise_ii]. Gaia Koolis viisin arvutiteaduse õppes läbi projekti küberkiusamise plakati tegemiseks[@a2025_kber; @a2025_kber_ovtsik]. Arvutiteaduse klubides olen lasknud hulganisti praktilisi ja loovaid tegevusi teha õpilastel, samuti informaatikaõppes üldiselt.
- Toetan **individuaalseid õpivajadusi**, jälgides õppijate edenemist ja pakkudes vajadusel täiendavat juhendamist või eritoetust. Osa õpilasi õpivad ainult siis, kui nendega üks-ühele tegelen.

Refleksioon on oluline osa õppimisprotsessist nii õpilastele kui ka õpetajale. Kasutan refleksioonimudeleid:
- **Õpilaste refleksioon**: Julgustan õppijaid mõtisklema oma tugevuste, arenguvõimaluste ja edusammude üle, et suurendada eneseteadlikkust ja vastutustunnet. Näiteks KG's lasin õpilasel esmalt ise enda testisooritust hinnata, misjärel võrdlesime minu hinnanguga.  
- **Õpetaja refleksioon**: Hindan regulaarselt oma õpetamise tõhusust ja kohandan meetodeid vastavalt klassi vajadustele. Kasutan näiteks Kolbi refleksioonimudelit (kogemus → vaatlus ja analüüs → järeldused → katsetamine)[@kolb84], et hinnata, kuidas minu tegevused mõjutavad õppimist ja klassi dünaamikat. Nt Peetri Lasteaed-Põhikoolis matemaatikaõpetajana iga kahe kuu järel vahetasin õppeallikat, et välja selgitada, milline allikas selle rühma õpilaste jaoks kõige paremini toimib.

Kokkuvõttes aitab teadlikkus õppimist mõjutavatest teguritest ja tõenduspõhistest võimalustest luua toetava ja arengut soodustava keskkonna, kus õppijad saavad arendada oma potentsiaali nii individuaalselt kui ka grupis. Refleksioon on seejuures oluline tööriist, et pidevalt täiustada õppetööd ja vastata õppijate vajadustele.

Tegevusnäitaja:

> hoiab ennast kursis õppimist ja õppija arengut puudutava terminoloogia, uuema teadmuse ja uuringutega.

Õpetajana pean oluliseks pidevat professionaalset arengut, et tagada oma teadmiste ja oskuste vastavus muutuvatele haridusvajadustele. Jälgin regulaarselt õppimist ja õppija arengut käsitlevaid uuringuid, uuemaid teooriaid ning terminoloogiat, et pakkuda kaasaegset ja tõhusat õpet.

Olen kursis haridusterminoloogiaga, mis puudutab näiteks:
- **kognitiivset arengut** (nt Bloom’i taksonoomia, Vygotsky lähima arengu tsoon[@lambright_2023_the]),
- **õppimisprotsessi juhtimist** (nt formatiivne hindamine, aktiivõpe, metakognitiivsed strateegiad[@melisyeilpnaruyar_2024_metacognitive]),
- **emotsionaalset ja sotsiaalset arengut** (nt emotsionaalne intelligentsus, sotsiaal-emotsionaalne õpe).

Tegutsen selle nimel, et kasutada tundides täpset ja arusaadavat sõnavara ning õpetan seda ka õpilastele, et suurendada nende teadlikkust õppimisprotsessidest. Pean oluliseks üheselt mõistetavust ja kirjeldatavust, mistõttu eelistan kasutada sellist terminoloogiat, mis päriselt kirjeldab objekti, mille jaoks termin on. Kui teen tahvlile jooniseid või kirjutan lahti valemeid, lisan mõisted (\@ref(fig:support-circular-motion)).

```{r label = "support-circular-motion", echo=FALSE, fig.cap = "Ringliikumise teooria kompaktselt koos mõistetega."}
include_external_graphics("rmd/ringliikumine-IMG_20250117_161555.jpg")

```

Hoian end kursis haridusvaldkonna uusimate uuringutega, lugedes teadusartikleid, uurimisraporteid ja erialakirjandust. Selleks kasutan:
- **rahvusvahelisi teadusajakirju ja andmebaase**, nagu MyEBSCO[@a2025_eandmebaasidesse],
- **Eesti haridusalaseid väljaandeid ja uuringuid**, näiteks Tartu Ülikooli ja Tallinna Ülikooli haridusteaduste teaduskondade töid,
- **konverentse ja koolitusi**, kus jagatakse uusimaid teadmisi ja praktikaid[@a2025_isikukaartasice].

Näiteks olen uurinud, kuidas õpetamiseks valmistumine tõhustab õppimist[@guerrero_2021_expecting].

Püüan rakendada teaduspõhiseid lahendusi oma igapäevases õpetamispraktikas. Näiteks olen:
- integreerinud **aktiivõppe meetodid** tundidesse, et soodustada õppijate sügavamat kaasatust ja kriitilist mõtlemist,
- kasutanud **formatiivse hindamise põhimõtteid**, et anda õpilastele pidevat ja konstruktiivset tagasisidet (lühitestid, enda ja kaaslase soorituse hindamine, suunamine veaotsingule),
- juhtinud **refleksiooniprotsesse**, et aidata õpilastel mõista oma õppimisprotsessi ja teha teadlikke otsuseid oma arengu suunas.

Osalen regulaarselt professionaalsetes koolitustes ja seminaridel, et täiendada oma teadmisi ja arendada uusi oskusi. Näiteks olen osalenud  pedagoogilistel koolitustel, mis käsitlevad **õppija digipädevuse toetamist**.

Samuti jagan oma teadmisi kolleegidega ja osalen haridusalastes aruteludes, et edendada professionaalset dialoogi ja õppimist koolimeeskonnas.

Pidev kursisolek õppimist ja õppija arengut puudutava terminoloogia, teadmuse ja uuringutega aitab mul olla paindlik ja tõenduspõhine õpetaja. See võimaldab mul luua õppekeskkonna, kus igal õppijal on võimalus saavutada oma täielik potentsiaal ning kus minu õpetamispraktika on ajakohane ja teadlik.

Tegevusnäitaja:

> on teadlik digilahenduste kasutamise võimalustest ja sellega seotud riskidest õppimisel.  

Digilahenduste kasutamine hariduses pakub mitmeid võimalusi õppimise mitmekesistamiseks, kohandamiseks ja toetamiseks, kuid samas kaasneb sellega ka mitmeid riske, mida õpetajana teadvustan ja oskan ennetada. Minu eesmärk on kasutada digivahendeid teadlikult ja tõhusalt, et toetada õppijate arengut ning edendada nende digipädevust.

Digivahendid aitavad muuta õppimist kaasavamaks, paindlikumaks ja motiveerivamaks. Kasutan tehnoloogiat nii teadmiste omandamise kui ka süvendamise eesmärgil. Peamised võimalused, mida digilahendused pakuvad:  

- **personaalne ja kohandatud õpe**:  
  - e-õppeplatvormid (nt Moodle, Google Classroom) võimaldavad õppijatel liikuda omas tempos ja saada individuaalset tagasisidet,  
  - kohandatud õppematerjalid (nt adaptiivne tarkvara, nagu Khan Academy) võimaldavad õppijatel harjutada just neid teemasid, milles nad vajavad rohkem tuge.  

- **interaktiivsed ja koostööpõhised õpimeetodid**:  
  - digitaalsete tööriistade (nt Answergarden[@creativeheroesnl_2024_answergarden; @creativeheroesnl_2024_answergarden_6]) abil saavad õpilased väljendada oma arvamusi ja osaleda aruteludes,  
  - koostööplatvormid (nt Google Docs, Microsoft Teams) võimaldavad õpilastel töötada ühiselt ka väljaspool klassiruumi.  

- **visuaalne ja multimeediaõpe**: õppevideod, simulatsioonid ja interaktiivsed rakendused muudavad keerukad teemad arusaadavamaks ning aitavad toetada visuaalseid ja kinesteetilisi õppijaid,  

- **reaalajas tagasiside ja hindamine**: formatiivse hindamise tööriistad (nt Plickers) aitavad õpetajal kiiresti hinnata õppijate arusaamist ja kohandada õpet vastavalt vajadusele.  

Kuigi digitehnoloogia pakub hariduses palju eeliseid, on oluline teadvustada ka sellega kaasnevaid riske ning võtta meetmeid nende ennetamiseks:  

- **infoturbe ja privaatsuse kaitse**:  
  - õpetajana hoolitsen selle eest, et õpilased teaksid, kuidas kaitsta oma isikuandmeid ja järgida turvalise internetikasutuse põhimõtteid,  
  - kasutan turvalisi ja usaldusväärseid platvorme ning teavitan õpilasi võimalike ohtude, nagu andmepüük ja identiteedivargus, kohta,  

- **digivahendite liigkasutamine ja ekraaniaja tasakaal**:  
  - toetan tasakaalu digitaalse ja traditsioonilise õppimise vahel, et vältida õpilaste liigset sõltuvust tehnoloogiast,  
  - julgustan aktiivset ja praktilist õppimist ning soodustan õpilaste omavahelist suhtlemist ka väljaspool digitaalset keskkonda,  

- **info üleküllus ja kriitilise mõtlemise arendamine**:  
  - õpetan õpilastele allikakriitikat, et nad oskaksid eristada usaldusväärset infot väärinfost,  
  - kasutan teaduspõhiseid ja kvaliteetseid allikaid ning julgustan õpilasi hindama ja võrdlema erinevaid seisukohti,  

- **küberkiusamine ja eetikaküsimused**:  
  - selgitan õpilastele digikäitumise põhimõtteid, rõhutades netiketi ja austava suhtlemise olulisust,  
  - jälgin klassi digisuhtlust ja reageerin probleemidele, toetades turvalist ja toetavat õpikeskkonda.  

Kui õpilased ise digivahendeid kasutavad, siis on oht või võimalus, et nad kasutavad neid enamaks, kui õppesessiooni plaanis on ette nähtud. See võib olla neile nii abiks kui ka takistuseks. Jaak Aaviksoo on väitnud, et mängude mängimise kaudu võivad lapsed arendada endis vajalikke oskusi[@a2024_etv, 30:56-31:13]. Kui ma esimestes matemaatika ja informaatika õpetamisaastates kuni kolmanda astme õpilastele piirasin nende ligipääsu mitteaktsepteeritud mängudele, siis enam ma seda ei tee. Olen täheldanud, et kui õpilane mängib oma mänguisu täis, asub ta tegelema õppesessiooniks ettenähtud sisuga.

Õpetajana ei ole minu ülesanne ainult digivahendite kasutamine, vaid ka õpilaste juhendamine teadlikuks ja vastutustundlikuks digikasutajaks saamisel. Minu roll hõlmab:  
- **õpilaste juhendamist digivahendite tõhusas ja eesmärgipärases kasutamises**, et nad oskaksid tehnoloogiat rakendada õppimise ja enesearengu toetamiseks,  
- **digitaalsete õpioskuste ja meediakirjaoskuse arendamist**, et õpilased suudaksid infoühiskonnas teadlikult ja kriitiliselt toimetada,  
- **kriitilise mõtlemise ja probleemilahendusoskuste kujundamist**, et õpilased oskaksid digimaailmas tekkivaid väljakutseid analüüsida ja lahendada.  

Olles teadlik digilahenduste võimalustest ja riskidest, kasutan tehnoloogiat õppimise toetamiseks läbimõeldult ja vastutustundlikult. Pööran tähelepanu nii digipädevuste arendamisele kui ka ohutusele, et aidata õpilastel kujuneda teadlikeks ja iseseisvateks õppijateks, kes oskavad tehnoloogiat kasutada mõtestatult ja vastutustundlikult.

### Õppija tundmaõppimine

Tegevusnäitaja:

> selgitab välja rühma ja õppija ainealase, õpioskuste ja õpimotivatsiooni taseme ning arvestab neid (ainevaldkondlike, üldpedagoogiliste ja kasvatuslike) õpieesmärkide seadmisel.  

Õpetajana pean oluliseks, et õppetöö lähtuks õppijate tegelikest vajadustest, võimetest ja huvidest. Seetõttu teen teadlikke pingutusi, et mõista nii klassi kui ka iga üksiku õppija ainealast taset, õpioskusi ja õpimotivatsiooni. See teave on minu jaoks võtmetähtsusega, et seada realistlikke ja arendavaid õpieesmärke, mis toetavad nii akadeemilist kui ka sotsiaalset arengut.

Õppijate ainealase taseme hindamine aitab mul mõista, milliseid eelteadmisi nad omavad ja millised valdkonnad vajavad täiendavat toetust. Selleks kasutan erinevaid meetodeid:
- **diagnostilised testid ja sissejuhatavad ülesanded**, et selgitada välja õppijate varasemad teadmised ja võimalikud lüngad,
- **vestlused ja arutelud**, et saada ülevaade õppijate enesehinnangust ja varasematest kogemustest ainega,
- **formatiivne hindamine** (nt arutelud, lühikesed kontrollküsimused, enesehindamine), et jälgida jooksvalt õppijate arengut ja teha vajalikke kohandusi õppetöös.

Nt NTK's kirjutasin tahvlile kompleksjuuravaldise ja küsisin, kas keegi seda lahendada oskab. Kui oleks osanud, märkinuksin talle maksimaalse hinde ja suunanuksin ta järgmisse alateemasse. Järgnevalt selgitasin sammhaaval, kuidas seda avaldist lihtsustada.

Tallinna Polütehnikumis viisin läbi vestlusi sisseastujatega.

Formatiivset hindamist teen sageli, et õpilased n-ö õigelt teelt kõrvale ei kalduks.

Saadud info põhjal planeerin diferentseeritud õpet, kus võtan arvesse erinevaid tasemeid ja pakun täiendavaid toetavaid materjale neile, kes seda vajavad.

Õpioskused, nagu ajaplaneerimine, teksti mõistmine, info analüüsimine ja probleemilahendusvõime, on õppimise edukuse võtmetegurid. Nende taseme hindamiseks:
- **jälgin õpilaste tööprotsessi**, sealhulgas seda, kuidas nad lahendavad ülesandeid ja töötlevad infot,
- **küsin refleksiooniküsimusi**, et aidata neil mõista ja hinnata oma õppimisviise,
- **jälgin eneseregulatsiooni oskusi**, näiteks kas õpilane suudab iseseisvalt planeerida oma tööd ja õppida järjepidevalt.

Soovin, et õpilane näitaks kogu oma lahenduskäiku, et mõistaksin, kuidas ta mõtleb.

Kui märkan, et mõnel õppijal on raskusi näiteks aja planeerimise või materjali sügavama mõistmisega, toetan neid sihipäraselt, näiteks suunates neid märkmeid tegema või kasutama metakognitiivseid strateegiaid.

Õpimotivatsioon mõjutab oluliselt seda, kuidas ja kui sügavalt õppija teemasse süveneb. Motiveerimiseks on oluline mõista,
- **mis on õpilase huvid ja eesmärgid**: kas õpilane õpib aine vastu isiklikust huvist või pigem hinnete pärast,
- **millised tegurid mõjutavad motivatsiooni**: kas õpilane vajab rohkem tunnustust, selgemat eesmärgistamist või praktilisi ülesandeid,
- **kas õpilasel on sisemine või väline motivatsioon**: õpin üles ehitama õppetööd nii, et see toetaks eelkõige sisemist motivatsiooni, pakkudes tähenduslikke ja päriseluga seotud ülesandeid.

Motiveerimise toetamiseks:
- **seon õpitava õpilaste igapäevaeluga**, et nad näeksid selle praktilist väärtust,
- **kasutan aktiivõppe meetodeid**, et muuta tunnid kaasahaaravamaks,
- **toetan positiivset tagasisidet ja eduelamusi**, et õpilased tunneksid, et nende pingutused on väärtustatud.

Kui olen saanud ülevaate õppijate tasemest ja vajadustest, saan seada **reaalsed, saavutamist toetavad õpieesmärgid**, mis hõlmavad:
- **ainealaseid eesmärke**, mis vastavad õpilaste eelteadmistele ja arenguvõimalustele,
- **üldpedagoogilisi eesmärke**, mis arendavad õppijaid kui terviklikke mõtlejaid ja probleemilahendajaid.
- **kasvatuslikke eesmärke**, mis toetavad sotsiaalseid oskusi, vastutustunnet ja iseseisvust.

Õpieesmärkide seadmisel rakendan **diferentseeritud õpet**, et iga õpilane saaks endale sobiva väljakutse:
- pakun **valikuvõimalusi**, et õppijad saaksid ülesandeid kohandada vastavalt oma tugevustele ja huvidele,
- kasutan **järkjärgulist juhendamist**, et toetada keerulisemate oskuste arengut,
- jälgin regulaarselt õppijate arengut ning kohandan eesmärke vastavalt vajadusele.

Nt NTK's tuvastasin ühe gümnasiasti puhul, et ta ei osanud liita ühekohalisi arve. Seetõttu trükkisin talle lehe ühekohaliste arvude liitmise ülesannetega, et ta saaks harjutada ja oma lünga täita.

Teades oma õpilaste ainealast taset, õpioskusi ja motivatsiooni, saan pakkuda **eesmärgipärast, diferentseeritud ja toetavat õpet**. See võimaldab igal õppijal liikuda oma võimete piires edasi, arendada vajalikku enesejuhtimisoskust ning tunda õppimisest rõõmu ja rahulolu.

Tegevusnäitaja:

> kogub koostöös kolleegidega õppeprotsessist infot ja uurib võimalusi, kuidas toetada õppija terviklikku arengut ja valmisolekut õppimiseks  

Õpetajana on minu eesmärk mõista iga õppijat terviklikult – mitte ainult tema ainealaseid oskusi, vaid ka tema õpioskusi, motivatsiooni ja heaolu. Selleks teen koostööd kolleegidega, et koguda mitmekülgset infot õppeprotsessist ning leida tõenduspõhiseid ja paindlikke lahendusi, mis toetavad õppija arengut.

Õppijate toetamiseks on oluline koguda pidevat ja mitmekesist tagasisidet, et mõista, kuidas nad õppetöös edenevad ja millist tuge nad vajavad. Selleks kasutan erinevaid meetodeid:
- **õpilaste tööde ja hinnangute analüüs** – jälgin nende õpitulemusi, enesehindamisi ja õppeprotsessis ilmnevaid raskusi,
- **formatiivne hindamine** – kasutan diagnostilisi ülesandeid, enesehindamist ja refleksiooni, et selgitada välja õppijate tugevused ja arengukohad,
- **õpilaste ja kolleegide tagasiside** – küsin õpilastelt, kuidas nad oma õppimist tajuvad, ning teen koostööd teiste õpetajatega, et saada ülevaadet õppijate üldisest arengust.

Andmete analüüsimisel püüan märgata **õppemustreid ja võimalikke takistusi**, mis võivad mõjutada õppija edukust.

Tõhus õpilaste toetamine eeldab **meeskonnatööd ja kogemustest rääkimist**. Seetõttu teen regulaarselt koostööd:
- **aineõpetajatega**, et mõista, kuidas õppija areneb eri õppeainetes ja kas tema raskused on ainelised või üldised,
- **klassijuhatajaga**, kes omab ülevaadet õppija käitumisest, suhtlemisoskusest ja üldisest toimetulekust,
- **tugispetsialistidega** (eripedagoogid, psühholoogid, logopeedid), et leida sobivaid lahendusi õpiraskustega õppijatele,
- **õpilase ja tema vanematega**, et kaasata kodust tuge ja pakkuda õppijale järjepidevat tuge nii koolis kui ka väljaspool seda.

Näiteks, kui märkame koos kolleegidega, et mõni õppija vajab rohkem toetust enesejuhtimise ja õpioskuste arendamisel, otsime ühiselt lahendusi – kas läbi individuaalse õppekava, juhendatud õppimise või täiendavate õppematerjalide.

Õppimine ei sõltu ainult ainealastest teadmistest, vaid ka emotsionaalsest ja sotsiaalsest valmisolekust. Seepärast pean oluliseks:
- **õppija emotsionaalse heaolu jälgimist** – kui õppija tunneb end klassis turvaliselt ja toetatuna, suudab ta paremini keskenduda ja pingutada,
- **motivatsiooni ja eneseusaldust arendavaid meetodeid** – näiteks kasutan tunnis ülesandeid, mis võimaldavad õpilastel kogeda eduelamusi ja vastutada oma õppeprotsessi eest,
- **sotsiaalsete oskuste arendamist** – julgustan õpilasi koostööle, üksteise toetamisele ja konstruktiivsele suhtlemisele.

Kui märkan, et mõni õppija vajab rohkem tuge, kaasame kolleegidega tugimeeskonna ning otsime võimalusi, kuidas teda kõige paremini toetada.

Kuna iga õppija on erinev, on oluline **kohandada õpet lähtuvalt tema vajadustest**:
- Kui õppijal on **raskusi ainealases õppes**, saan pakkuda täiendavat juhendamist või individuaalseid ülesandeid.
- Kui õppija vajab **rohkem struktuuri ja planeerimist**, aitan tal õppimist paremini korraldada, jagades ülesandeid etappideks.
- Kui õpilane tunneb end **motivatsioonipuuduse või stressi tõttu ülekoormatuna**, otsime koos võimalusi, kuidas tasakaalu taastada.

Koostöös kolleegidega analüüsin regulaarselt, **kuidas meie meetodid aitavad õppijatel edeneda**, ning kohandan vajadusel oma õpetamispraktikat. Selleks:
- osalen aruteludes ja koolitustel, et täiendada oma teadmisi õpilaste toetamise ja õppimist toetavate meetodite osas,
- jagan kolleegidega parimaid praktikaid ja uusi teadmisi, et koos leida parimaid lahendusi,
- kasutan refleksioonimudeleid, et analüüsida oma õpetamise tõhusust ja õppijate arengut.

Õpilase tervikliku arengu toetamine on meeskonnatöö, mis nõuab süsteemset info kogumist, analüüsimist ja rakendamist. Tänu koostööle kolleegidega saan pakkuda õppijatele teadlikku ja sihipärast tuge, mis aitab neil **kasvada iseseisvaks, motiveeritud ja tasakaalustatud õppijaks**.

Tegevusnäitaja:

> kasutab arenguvestlusi õppija arengu toetamiseks.  

Arenguvestlused on minu kui õpetaja jaoks oluline tööriist, et toetada õppija individuaalset arengut ja õppimise protsessi. Need vestlused aitavad mõista õppija tugevusi, arenguvajadusi, motivatsiooni ning võimalikke takistusi, millega ta õpingute jooksul kokku puutub. Minu eesmärk on, et arenguvestlused oleksid suunatud õppija eneseteadlikkuse ja vastutustunde suurendamisele, pakkudes talle tuge ja julgustust individuaalse ja akadeemilise arengu teel.

Arenguvestluste läbiviimisel lähtun süsteemsest ja toetavast lähenemisest, mis hõlmab järgmisi etappe:
1. **Vestluse ettevalmistamine** – kogun andmeid õppija õpitulemuste, oskuste ja käitumise kohta ning julgustan õppijat enne vestlust ise oma arengut analüüsima.
2. **Vestluse läbiviimine** – loon usaldusliku õhkkonna, kus õppija tunneb end kuulatuna ning saab ausalt väljendada oma mõtteid, tundeid ja eesmärke.
3. **Tulemustest lähtuvalt eesmärkide seadmine** – aitan õppijal seada realistlikke ja saavutamist toetavaid sihte, mis arvestavad tema individuaalseid vajadusi.
4. **Edasine jälgimine ja tugi** – koostan koos õppijaga tegevusplaani ning jälgin tema edasist arengut, pakkudes vajadusel täiendavat juhendamist või tuge.

Arenguvestluste käigus keskendun mitmele olulisele aspektile:
- **Õpitulemused ja õpiedukus**:  
  - Analüüsime õppija tugevusi ja arenguvõimalusi konkreetsetes õppeainetes.  
  - Arutleme, millised õpistrateegiad on olnud tõhusad ja milliseid võiks muuta.  

- **Õppija motivatsioon ja huvid**:  
  - Uurin, mis motiveerib õppijat ja millised on tema eesmärgid õppetöös.  
  - Selgitame välja, kas õppijal on huvisid või karjäärialaseid eesmärke, mis võiksid mõjutada tema õpivalikuid.  

- **Õpioskused ja enesejuhtimine**:  
  - Arutame, kuidas õppija planeerib oma õppetööd ja ajajuhtimist.  
  - Vajadusel pakun soovitusi tõhusamate õppimistehnikate ja enesejuhtimise oskuste arendamiseks.  

- **Sotsiaalne ja emotsionaalne heaolu**:  
  - Annan õppijale võimaluse rääkida oma enesetundest ja koolikogemusest.  
  - Kui õppija kogeb stressi või õpiraskusi, otsime üheskoos võimalusi nende lahendamiseks.  

Kuna iga õppija on erinev, kujundan arenguvestlused **paindlikult ja õppijakeskselt**, arvestades,
- kas õppija vajab **täiendavat juhendamist ja tuge** või hoopis rohkem väljakutseid,
- kas ta tunneb end koolikeskkonnas **motiveerituna ja enesekindlalt** või vajab lisajulgustust,
- millised **individuaalsed eesmärgid ja vajadused** võiksid mõjutada tema õpiteekonda.

Kui vestluse käigus selgub, et õppijal on erivajadusi või takistusi, suunan ta vajadusel tugispetsialistide juurde või kohandan õpet, et pakkuda talle sobivamat tuge.

Arenguvestluste tõhususe tagamiseks:
- **Koostöötan teiste õpetajate ja tugispetsialistidega**, et saada terviklik ülevaade õppija arengust ja toetusvajadusest.  
- **Kaasan lapsevanemaid**, kui see on vajalik, et õppija saaks kodus täiendavat tuge ja julgustust.  
- **Annan ja küsin regulaarset tagasisidet**, et õppija tunneks end kaasatuna ja vastutavana oma õpiteekonna eest.  

Vestlusi arengust olen õpilastega läbi viinud eelkõige üks-ühele ja väikese rühmaga õppes, sest suure rühma puhul ei ole selleks piisavat ajavaru. Vestlused on toimunud informaalselt, mistõttu ei eksisteeri nende kohta kirjalikku dokumentatsiooni.

Arenguvestlused on minu õpetamispraktikas väärtuslik tööriist, mis aitab luua õppijakeskse ja toetava õpikeskkonna. Teadvustades õppija individuaalseid vajadusi ja pakkudes talle struktureeritud tagasisidet ning juhendamist, saan aidata tal kujundada **enesekindlust, õpioskusi ja motivatsiooni**, mis toetavad tema pikaajalist arengut ja edu.







### Õppija taust

Et tõhusalt õpetada, on vaja lähtuda õppija tasemest. Kui tema teadmistes ja oskustes esineb lünki, siis on vaja need esmalt täita.

Kui õpilase õpimotivatsioon on madal, tuleb proovida eri meetodeid, et välja selgitada, milline meetod võiks ta õpimotivatsiooni suurendada. Võib selguda, et õpilane õpibki valet asja või vales ajas.

Kui õpilane minu õpetatavas valdkonnas ei edene, siis uurin, kuidas ta edeneb muudes valdkondades. Kui selgub valdkond, milles ta edeneb, siis püüan lõimida seda valdkonda enda õpetatavasse valdkonda. Nt on mul füüsika ja keemia õppes õpilane, kes vihkas matemaatikat. Ühtlasi on ta lummatud muusikariistade kasutamisest. Seega püüdsin füüsikaülesandeid seostada muusikainstrumentidega.

Et välja selgitada õpilase hetke motivatsioon ja tema sihid, siis võimalusel vestlen nendest õpilasega. Suure rühma puhul ei ole selleks piisavat ajavaru ning siis hangin selle info rühmajuhilt või muudelt õpetajatelt, kellel võib see info olla. Kui tegemist on üksikute probleemsete õpilastega, siis vahel vestlen nendega, kuid pigem on see rühmas minu puhul ikkagi harv näht. Üks-ühele õpetamises selgitan muidugi alati õpilasega vesteldes välja eesmärgi.

### Individuaalsed õpivajadused

Kuna kõik õpilased on erinevad, siis on neil ka erinevad õpivajadused. Olen jõudnud pärast aastatepikkust õpetamist suurtes rühmades individuaalsete plaanide koostamise ja järgimiseni. Alustan kõigiga samal tasemel. Juba esimesel või teisel korral viin läbi lühitesti, mille põhjal selgub, kellel on teemasse vaja rohkem süübida, kes võib juba järgmise teema võtta. Vastavalt sellele annan iga õppesessiooni alguses õpilastele vastavalt plaanile ülesanded. Kõige edukamatega jätkan tahvli abiga. Vahel on tahvli abi vaja ka muude õpilaste jaoks.

Kui koolis on tugispetsialiste, siis suhtlen nendega, et arutada konkreetsete õpilastega toimetulemist. Igas koolis pole ja nii tuleb oma jõuga või rühmajuhi abiga toime tulla. Tugispetsialistil on üldiselt info probleemsete õpilaste kohta. Kuna ma ei ole eripedagoog ega taotle ka selleks saamist, siis võtan vaid nii palju enda kanda, kui suudan olles mitteeripedagoog, et teatud õpilast aidata. Olen õppinud, et üldharidussüsteemis võidab õigus õigluse, sest see pole optimaalne süsteem ja kõiki õpilasi aidata ei saagi ega tohigi oma õpitut raisata, kui on olemas neid, kes sellest võiksid profiteerida. Seega, kui mulle öeldakse, et ainuüksi kohalkäimise eest tuleb *3* panna, siis ma seda teen kirjutades kommentaariks, et see ei näita õpiväljundite saavutatust.

Vahel tekib mus tunne, et on vaja teatada midagi õpilase hooldajale. Siis teen seda. Vahel võtab hooldaja minuga otse ühendust. Siis vestleme. Minu siht on konsensus. Ilma selleta ei toimu tõhusat õppimist. Vaja on, et kõik asjaosalised saaksid ühtmoodi aru. Selleks palun vajadusel ühist koosolekut, milles osalevad õpilane, tema hooldaja, mina, õppejuht, direktor.

### Sotsiaalsus

Sotsiaalsete ja koostööoskuste arengut on lihtne toetada tennises, milles suunan õpilasi arvestama üksteisega paarismängus või koostöö harjutuses. Ka n-ö pehmetes teemades teen seda aegajalt suunates õpilasi ühisesse arutellu. Hiljuti viisin läbi teadmiste-oskuste testimise, milles testitavad võisid omavahel arutleda, kuid muude abivahendite kasutamine polnud lubatud. Õppija, kes arvas enne testimist, et viib kaasõpilase hinde alla, hoopis aitas oma mõtetega kaasõpilast ja tõstis seda.

Kursuse või õppeaasta alguses, kui kursuseid pole, alustan enda reeglite teavitamisest, misjärel soovin õpilastelt tagasisidet ning kui kellelgi on ettepanekuid reeglite muutmiseks, siis arutame ja kui jõuame konsensuseni, muudame.

Olen korraldanud rühmiti teadmiste-oskuste testimist looduses, milles kõik abivahendid lubatud.

Ühtsustunde toetamine võib olla nii positiivses kui negatiivses võtmes. Nt kui on distsipliiniprobleem, et õpilased on niivõrd hoos pausi tegevustega ja lärmakad, et me ei saa õppesessiooni alustada, siis olen sellistes juhtudes lasknud õpilastel rahuneda ja öelnud, et alustame siis, kui viimne kui üks õpilane on vaikne ning kõik on seda samaaegselt.

## Õpi- ja õpetamistegevuse kavandamine

### Õpivara

Kui alustan kursust või õppeaastat, siis vaatan esmalt, mis on õppekavas kirjas, kui selle kohta, mida õpetan, on õppekava. Võtan õppekavast õpiväljundid ning teen skeemi, milles on sõltuvussuhted õpiväljundite vahel. Kaalun iga õpiväljundi vastavalt Bloomi taksonoomiale[@blooms]. Pikaajaline õpieesmärk on seega kõige selle saavutamine, mis on õppekavas ette nähtud. Lühiajalised eesmärgid on vastavad õpiväljundid. On esinenud olukordi, milles soovitatakse vältida õppekava ja mõelda, mida õpilastel päriselt vaja läheb. Siis olen lähtunud sellisest soovitusest.

Valin alati õpivara ise, kui see pole sätitud paika tööandja või muud tüüpi lepingupartneri poolt.

Kui märkan õpivara puudusi, pöördun esmalt õpivara autori või halduri poole, et temaga asjad korda ajada. Kui esineb liiga palju puudusi, mida ei likvideerita, siis teen ettepaneku organisatsiooni vastavale juhile õpivara muutmiseks, kui ma ise ei tohi seda muuta. Olen ka koostanud ise õpivara, mis on kõige tõhusam, sest saan seda muuta vastavalt vajadusele.

Valin õppevara eelkõige lähtuvalt sellest, et see oleks kasutatav kõigile globaalselt tasuta. Kui see pole kõigile globaalselt tasuta kättesaadav, siis peab see olema ülihea, et ma selle kasutusse võtaksin, või siis eksisteerib lepingupartneri poolne nõue. Opiq!! Foxcademy!!

Kuna ma jälgin, mida staarharidustehnoloogid teevad, siis katsetan ka ise erinevat õpivara ja kui veendun, et sobib, siis võtan kasutusse, kui lubatakse. Mul on plaan teha iseõppe tarkvara, mis baseerub vaiksele õpetamisele. Sellest eesmärgist lähtuvalt tasapisi loon ka ise õppevara. Näited seitsmenda mata jaoks!! 

### Õpikeskkonna kujundamine

Hindan kõrgelt püüdlemist elu poole, milles elatakse õnnelikult, heaolus, külluses, rahulolus ja tervises. See algab siia ilma sündinud inimese keskkonna mõjutustest. Kui too inimene kooli jõuab, on see mõjutus juba tehtud ja edasine mõjutamine omab väiksemat mõju. Kui õpilane veedab enamus aega väljaspool kooli, siis enamus aega saab ta mõjutusi väljaspool kooli. Nii palju kui võimalik soovin õpilase arengut lähtuvalt nimetatud eesmärkidest mõjutada koolis kujundades õpikeskkonna vastavalt.

### Organisatsiooni õpikeskkond

Võimalusel võtan osa õppenõukogu koosolekutest ja ütlen välja oma arvamuse. Väljendan ennast ka vastavalt vajadusele organisatsiooni poolt ette nähtud keskkondades toimuvates vestlustes, et tõhustada õpet.

## Õpetamine

### Huvidest digitehnoloogiateni

Individuaalne õppekava tagab õpilasele sobiva õppimise tempo. Sõltuvalt kogemustest on õpilased kokku puutunud eri valdkondadega. Sõltuvalt geneetilisest päritolust on neil erinev võimekus. Siiski on oluline neid suunata nende kõige kiiremas arenemisjärgus, sest neil pole piisavalt teadmisi ja oskusi, millele tugineda oma valikutest. Kogesin hiljuti, et gümnasiast ei osanud liita ühekohalisi arve ilma kalkulaatorita. See avastus ilmnes, kui tegelesime juurimisega. Kuna juurimine ei edenenud, proovisime astendamist täisarvulise astendajaga. Kuna ka see ei edenenud, liikusime korrutamise juurde. Kuna ka see ei edenenud, liikusime liitmise juurde ja nii see puudus avaldus. Seega koostasin tollele õpilasele ülesanded ühekohaliste arvude liitmise kohta, mille ta lahendas siiski edukalt, misjärel asusime astendamise juurde. Ei tohi sisse jätta lünkasid.

Kui õpilane suudab keskenduda vaid lühikeseks ajaks, siis tuleb talle anda lühikesi ülesandeid. Sõltuvalt ülesandest võib ka siis juhtuda, et õpilane saab ülesandest haaratud ja ta tahab jätkata pikemalt.

Mõnel inimesel on võimsam mälu, mõnel võimsam mõtlemine. Kui mälu napib, on abiks, kui õpilane märgib ülesande lahendamises vahetulemusi sagedamini üles.

Oma õpetamistegevuses alatasa katsetan, mis toimib, mis mitte. Kui märkan, et mingi meetod millegi õpetamiseks kellelegi ei toimi, siis proovin mingit muud meetodit, kuni leian sellise, mis toimib, või siis ei leiagi.

Õppijate arengu kohta ma üldiselt ülestähendusi ei tee, sest nende õpetamise kestel on mul alati ülevaade, kes on kuidas arenenud minu õpetamise kestel.

Kriiditahvlilt ei paista nii hästi kui digitahvlilt ja jooned pole nii sirged kui digitahvlil. Lisaks peab kriiditahvlit niisutatud lapiga puhastama, digitahvlil piisab kahest nupuvajutusest ning on võimalik ka tehtu suurust ja kuju muuta ning nihutada ja jupikaupa kustutada, samuti värvi muuta. Ka ei jää digitahvlit kasutades näpud kriidiseks. Ühtlasi pole ohtu, et markertahvli puhul kogemata püsimarkerit sai kasutatud. Digitahvli kasutamine hoiab kustutamise osas aega kokku. Kui ruumis on digitahvel, siis seda ikka kasutan. Kui on ka mittedigitahvel, siis vahel kasutan seda lisaks, et rohkem õpilasi oleks kaasatud. Nii kuvan ülesande nt digitahvlile ja keegi saab lahendada kriiditahvlile.

Vahel olen esmase kogemuste kaardistamise jaoks kasutanud keskkonda, millesse õpilased saavad märksõnu sisestada. Keskkonnale ligi saavad nad ruutkoodi kaudu, mille kuvan digitahvlile või projektoriga ekraanile, kasutades oma nutitelefoni.

Arvutiteaduses kasutame ohtralt sülereid, et iga õpilane saaks käed külge panna.

Õpilaste arengu jälgimiseks kasutan võimalusel selliseid digikeskkondi, kus selline jälgimine on võimalik. Sellised tasuta kasutatavad keskkonnad on enamasti arvutiteaduse õppe jaoks.

### Koostööst konfliktideni

Julgustan õpilasi vahel arutlema ühiselt. Vahel jaotan õpilased väikestesse rühmadesse üheskoos lahendama. On õpilasi, kes ei soovi muu õpilasega koos lahendada ning sellistel õpilastel võimaldan individuaalselt lahendada.

Kui osa õpilasi kipuvad häirima õpperahu, siis kutsun nad korrale selgitades õpperahu põhimõtet. Sõltuvalt koolist on sisse seatud süsteem, mis võimaldab õpetajal õpilase, kes ei rahune piisavalt kiiresti, saata iseseisvalt ülesannet lahendama tugispetsialisti juurde.

Valin õpivahendid selliselt, et nende kasutamine oleks piisavalt turvaline. Kui on vajalik kasutada ohutusabinõusid, siis neid eelnevalt selgitan õpilastele ja kontrollin, et nad on aru saanud, enne kui vastava tegevusega alustame.

Rühma areng algab rühma loomisest ning kestab läbi rühma liikmete üksteisega arvestamise.

Kui märkan, et õpilased omavahel nääklevad ja see häirib õppekeskkonda, siis uurin neilt, miks see nii on, ja kui on ajavaru, siis vestlen nendega ja suunan neid ühisele sobivale lahendusele. Kui mul seda ajavaru pole, kaasan tugispetsialisti või rühmajuhi.

Õpilase hoolsus kajastub sagedastes lühitestides hinnetena ja sõnalise tagasisidena. Kui õpilasel on tähtaegselt sooritus tegemata, siis sõltuvalt õppesüsteemist märgin selle kas tegemata ülesandeks või lisan märkuse, et ennetada arusaamatusi hilisema mitteaktsepteeritud sooritust kajastava hinde suhtes.

Et hindamine oleks läbipaistev, selgitan kursuse või õppeaasta alguses hindamissüsteemi ja teatan igast muudatusest ette. Kujundan hindamise selliseks, et see oleks mitte ainult õige, vaid ka õiglane.

Pakun õpilastele välja, et kõik saame etteantud piirides läbi rääkida. Konflikti korral on oluline ühekorraga konsensuseni läbi rääkida kõigil asjaosalistel, mitte eraldi tagaselja.

### Paindlik õpe

Iga õppija on eriline. Kui rühmas on palju õppijaid, siis igaühega eraldi arvestada ei ole otstarbekas. Rühm peaks koosnema ühtlase tasemega õpilastest. Siiski üldharidussüsteemis pole õpetajal midagi parata, kui talle on juba rühm moodustatud. Ometi saab teha korrektuure sõltuvalt kooli võimalustest. Nt saab moodustada eraldi õpperühmi mingis valdkonnas andekatele või mahajääjatele. Mina tekitan alates esimesest lühitestist individuaalse plaani ning kohandan seda sõltuvalt järjepidevate lühitestide tulemustest. Selles plaanis on sihiks õppeeesmärgid, mille võib saavutada rohkemate või vähemate vahetegevuste kaudu vastavalt õpilase vajadustele.

Võimalusel ilmestan õpiteemat lõimides muude valdkondadega. Leian, et tõhus on esmalt selgitada juppi teooriat, misjärel selle mõistmiseks ja kinnistamiseks lahendada hulganisti ülesandeid ning lõpuks võimalusel kontrollida teooriat praktiliselt. Vahel teen ka vastupidi lastes õpilastel avastada teooria, kuid see ei sobi kõigile.

Üks kord on mul ette tulnud, et rühmas on õpilane, kes liigub ainult ratastoolis. Tema puhul tuli arvestada, et ta saaks kõiki tegevusi sooritada oma kohal.

Paaril õpilasel on olnud probleeme heleda ekraanivalgustusega. Oleme lahendanud kas muutes taustavalgustust või õpilane on kasutanud vastavaid kaitseprille.

Kui õpilane on muidu hoolas ja huviga õppetegevuse juures, aga tempo on väike ja lahendamiseks kulub palju aega, on juhtunud, et ta varsti enam ei oska selliseid ülesandeid lahendada, mida ta alguses oskas lahendada. Sellistes juhtudes on mõistlik teha paus, vaheldada tegevusi.

Tugispetsialistile on üldiselt teada, kellel milline probleem on, ja ta mulle kui õpetajale sellest teavitab andes ühtlasi üldisi soovitusi, mida võimalusel arvestan.

### Eneseanalüüsist õpimotivatsioonini

Arvutiteadust õpetades kasutan projektihalduse tarkvara, millest õpilased vaatavad endale ülesandeid, peavad järge ja raporteerivad ajakulu.

Matemaatikat õpetades kasutan iga õpilase individuaalset järge. Kui õpilasel on miski ebaselge, siis annan talle selle teema kohta selgitavat teksti lugeda ja ülesandeid lahendada iseseisvalt või rühmakaaslasega koos. Kui ta tunneb, et tal on teema selge, testime. Olen ka andnud ühe õpilase sooritust teisele hinnata või lasta õpilasel ise hinnata oma sooritust.

Oluline on, et õppimine oleks ühtlasi jõukohane ja väljakutsuv. Et õppimine oleks jõukohane, peavad õppimiseks olema täidetud eeldused: sobilik õppekeskkond, sobilikud vahendid, null lünka vajalikes teadmistes-oskustes. Et õppimine oleks väljakutsuv, ei tasu liiga palju selliseid ülesandeid lahendada, mida nagunii osatakse lahendada, sest see muutub tüütuks, vaid võtta juurde selliseid, mille lahendamine ei kulge automaatselt. Selliseid väljakutsuvaid ülesandeid tuleb lahendada, kuni lahendamine muutub automaatseks.

### Digitehnoloogiatele suunamine

Arvutiteaduse õppes käsitleme info otsimist digitehnoloogiate abil.

Muudes valdkondades lasen aegajalt õpilastel nutitelefoniga otsida vastuse küsimusele. Vahel tuleb seejuures selgitada, kuidas küsida ja kust küsida, et saada võimalikult usaldusväärne vastus.

Arvutiteaduses rakendame digitehnoloogiaid mõtestatult alatasa. Muudes valdkondades teeme seda vastavalt vajadusele ja sobivusele.

### Tagasisidestamine

Tagasisidestan õpilastele alatasa. Sageli viin läbi lühiteste, millest saame selgust õpiväljundi saavutatuse osas. Õpilane saab hinde, mida on võimalik parandada järgmises lühitestis. Hindele lisandub kommentaar soorituse kohta vajadusel koos soovitusega.

Hindamismudelite koostamises olen laisk. Küll aga koostan hindamiskriteeriume. Teatan õpilastele, mis on vaja sooritada ja kuidas ma sooritusi hindan.

Olen lasknud õpilastel oma sooritust ise hinnata ja seejärel minu hindamisega võrrelda.

Tagasisidestamise reeglid olen tutvustanud kursuse või õppeaasta alguses ning andnud võimaluse teha muudatusettepanekuid. Vahel on tulnud reegleid muuta ja siis olen muutustest ette teatanud.

## Refleksioon ja professionaalne enesearendamine

### Professionaalsus

Õpetamise mõju analüüsin selle järgi, kuidas mingi kasutatud meetod on millegi õppimiseks kellegi jaoks toiminud. Edulugusid jagan kolleegidega ja muudegi inimestega.

Kaardistan õpilaste teadmisi ja oskusi järjepidevalt. Selle kaardistuse põhjal tean, kus keegi oma järjega on ning vastavalt teadmistele ja oskustele saan moodustada õppekooslusi.

Minu praegune plaan on saada piisavalt pädevaks õpetamaks kõiki loodusteadusi, matemaatikat, arvutiteadust ja tennist. Kui matemaatika, arvutiteaduse ja tennise puhul on mul vajalik baas olemas, siis loodusteaduste osas alustasin süvaõppimist kõrgkoolis. Ühtlasi osalen kohustuslikes õpetajakoolitustes ja valikuliselt nendes, mis haakuvad minu missiooniga.

Kasutan digikeskkondi igapäevaselt ja peamiselt nende kaudu õpingi.

### Haridusuuringute rakendamine

Loen aegajalt teadusartikleid õppimise tõhustamise kohta ning kui on välja selgitatud mingi tõhus meetod, siis katsetan seda oma õpilaste peal.

Õpilaste rühmad on sobilik katselabor õppemetoodika testimiseks. Üldiselt alustan meetoditest, mis on mul varem toiminud, ja kui näen ebakõla, siis proovin midagi muud.

Edulugusid jagan kolleegidega ja muude inimestega.

### Enda tervis

Pean enda tervist oluliseks, sest kui olen ise korras, saan aidata teisi. Füüsilise tervise korrashoiuks annan kehale piisavalt aeroobset ja anaeroobset koormust, toitun võimalikult keha-, aga ka vaimusõbralikult, tegelen enda jaoks meeldivate ja huvitavate tegevustega, kasutan meeldivaid ja kasulikke vahendeid.

Üldiselt püüan ise hakkama saada. Kui mul on mentor, siis aegajalt suhtlen temaga. Seiran teiste õpetajate õppesessioone ja vaatan, kuidas nemad toime tulevad. Arutan kolleegidega probleemseid situatsioone. Pakun lahendusi kolleegile ja saan abi kolleegilt.

## Koostöö ja juhendamine

### Usaldamisest teavitamiseni

Õppimine saab toimuda vastastikusel usaldusel.

Vajadusel arutlen õppija toetamist tugispetsialistiga ja rühmajuhiga, vahel õppejuhiga.

Õppe korraldusest teavitan asjaosalisi kohe õppe alguses ja vahetult pärast muutmist.

### Suhtlemine lapsevanemaga

Õpilane saab tagasisidet vahetult õppesessioonis ja testimiste põhjal, mille järgselt näeb seda infot ka lapsevanem.

Kuna õpilane veedab väljaspool kooli rohkem aega kui koolis, siis on oluline, et kodune keskkond õppimist soodustaks.

Vajadusel teavitan lapsevanemat probleemist ja kutsun arutellu.

Vajadusel põhjendan oma otsuseid lapsevanemale.

### Tegutsemine rühmas

Jagan enda edulugusid kolleegidega, arutan nendega enda ja nende probleeme, annan nõu, võtan nõu.

## Arendus-, loome- ja teadustegevus

### Kogukondlik populariseerimine

Füüsikaõpetajana saan erialaliidu e-kirju ja võtan osa nende korraldatavatest sündmustest.

Populariseerivates sündmustes olen seni pigem osalenud kui korraldanud. Tennises olen siiski korraldanud hulganisti sündmusi. Arvutiteaduses olen korraldanud klubisid.

### Dokumentide koostamine

Soovin alati olla kaasatud organisatsiooni arengut suunavate dokumentide koostamises. Loen ettepanekud läbi ja kui mul on muutmisettepanekuid, siis teen neid.

Füüsikaõpetajana olen osalenud erialaliidu sündmustes, kuid mitte korraldanud.

Kui mul on muudatusettepanekuid, teavitan nendest.

## Digipedagoogika rakendamine

### 








1. loob ja koostab juhend- ja metoodilisi materjale digivahendite rakendamiseks oma õppeasutuses; korraldab ja viib läbi digipädevuste arengut ja erinevate digivahendite mõtestatud kasutamist toetavaid sisekoolitusi; soovitab digivahendeid, nõustab ja abistab kolleege digivahendite leidmisel, kasutusele võtmisel ja turvalisel kasutamisel; tõhustab koostöös oma kooli õpetajatega digivahendite kasutamist õppetöös;
2. analüüsib organisatsiooni digitaristut ja teeb ettepanekuid selle kaasajastamiseks ning rakendamiseks õppeprotsessis; hindab turvariske ja teeb ettepanekuid nende maandamiseks;
3. toetab ja hindab digivahendite väljapakkumise ja digipädevuse õppetöösse lõimimisega õppekava arendustööd.






# Teadlikkus õppija arengust ja õppimisest

Vasta nendele kutsestandardi tegevusnäitajatele põhinevatele küsimustele:

1.1.1 Kuidas arvestan oma töös õppija eripäradega (füüsiline, kognitiivne, emotsionaalne, kultuuriline, sotsiaalne areng)?

1.1.2 Kuidas toetan õppija üldpädevuste arengut ja grupiprotsesse?

1.1.3 Kuidas hoian ennast kursis õppimist ja õppija arengut puudutava uuema teadmusega (uuringud, terminoloogia)?

1.1.4 Milliseid digilahendusi kasutan õppija toetamisel? Nendega seotud riskid?


Tõendusvõimalused e-portfoolios. NÄITEKS: lingid, fotod, kirjeldused, näited, kuva-tõmmised, viited artiklitele jne 

Kirjeldan õppijate eripärasid ja õppija üldpädevuste arengu toetamist ja grupiprotsesse näidete varal. Esitan kirjelduse ja analüüsi kasutades õppija toetamise tõenduspõhiseid võimalusi ja refleksioonimudeleid, viitan allikatele.



1.2 Õppija tundmaõppimine

 

1.2.1 Kuidas selgitan välja õppija ja rühma ainealase taseme, õpioskused, -motivatsiooni?

1.2.2 Kuidas teen koostööd kolleegidega õppeprotsessist info kogumiseks?

1.2.3 Kuidas toetan õppija terviklikku arengut ja valmisolekut sh arenguvestluste kaudu?


Tõendusvõimalused e-portfoolios. NÄITEKS: lingid, fotod, kirjeldused, näited, kuva-tõmmised, viited artiklitele jne 

Analüüsin ja arutlen lähtudes oma kogemustest. Kirjeldan erinevaid võimalusi info kogumiseks toon näiteid. Analüüsin  arenguvestluse praktikat õppija toetamiseks. Arenguvestluste dokumentide näidised.



1.3 Õppija individuaalsete õpivajaduste toetamine


1.3.1 Kuidas selgitan välja tuge vajava õppija vajadused (individuaalsed õpivajadused sh teistest võimekam õppija)?

1.3.2 Kuidas kaasan tugispetsialiste, kolleege ja lapsevanemaid õppija toetusvajaduste väljaselgitamisel, õppe- ja arendustegevuse planeerimisel ning rakendamisel?

1.3.3 Kuidas leian sobiva õppemetoodika ja -vormi, jõukohastan õppe (kohandan õppematerjali, rakendan abivahendeid)?


Tõendusvõimalused e-portfoolios. NÄITEKS: lingid, fotod, kirjeldused, näited, kuva-tõmmised, viited artiklitele jne 

Analüüsin, arutlen, toon näiteid (individuaalne arengukaart, lapsevanemate nõustamine, kohandatud õppematerjalid).


1.4 Koostöise õppija kujundamine


1.4.1 Kuidas töötan välja ja visualiseerin ühistel väärtustel põhinevad kokkulepped koostöös õppijatega?

1.4.2 Kuidas suunan õppijaid üksteisega arvestama ja toetama võttes arvesse rühmaprotsesse ja dünaamikat?

1.4.3 Kuidas toetan ühtsustunnet oma koolis?


Tõendusvõimalused e-portfoolios. NÄITEKS: lingid, fotod, kirjeldused, näited, kuva-tõmmised, viited artiklitele jne 

Kirjeldan rühmaprotsesse ja toon näiteid (fotod visualiseeritud klassi reeglitest) oma praktikast.

